/**
 * ============================================================================
 * TrackFit Demo Athlete Generator
 * ============================================================================
 *
 * PURPOSE
 * -------
 * This file creates fake athlete profiles for development testing.
 *
 * Difficulty
 * ----------
 * ⭐⭐☆☆☆
 *
 * Why this exists
 * ---------------
 * A Coach engine needs different kinds of athletes to test against.
 *
 * Example:
 *
 * - a beginner should have simple progress
 * - an intermediate athlete should have steady history
 * - a plateau athlete should show stalled lifts
 * - a fatigued athlete should show too much recent training
 *
 * That means we can test Coach Intelligence without manually typing fake data
 * into the app every time. Developer Tools becomes mission control.
 *
 * ============================================================================
 */

import { seedDemoData } from "./demoSeedData";
import {
  CardioRepository,
  CheckInRepository,
  HistoryRepository,
} from "./trackfitDataLayer";

const PROFILE_SETTINGS = {
  beginner: {
    label: "Beginner Athlete",
    volumeMultiplier: 0.75,
    progressStep: 1.25,
    sleepBase: 7.2,
    proteinBase: 155,
    waterBase: 2.8,
    weightStart: 108,
    fatiguePattern: "normal",
    plateau: false,
  },
  intermediate: {
    label: "Intermediate Athlete",
    volumeMultiplier: 1,
    progressStep: 2.5,
    sleepBase: 6.8,
    proteinBase: 180,
    waterBase: 3.3,
    weightStart: 104.8,
    fatiguePattern: "normal",
    plateau: false,
  },
  plateau: {
    label: "Plateau Athlete",
    volumeMultiplier: 1,
    progressStep: 0,
    sleepBase: 6.6,
    proteinBase: 175,
    waterBase: 3.1,
    weightStart: 105.2,
    fatiguePattern: "normal",
    plateau: true,
  },
  fatigued: {
    label: "Fatigued Athlete",
    volumeMultiplier: 1.15,
    progressStep: 1.25,
    sleepBase: 5.6,
    proteinBase: 160,
    waterBase: 2.6,
    weightStart: 104.2,
    fatiguePattern: "heavy",
    plateau: false,
  },
};

const MUSCLES_BY_PATTERN = {
  horizontal_push: ["chest", "shoulders", "triceps"],
  vertical_push: ["shoulders", "triceps"],
  horizontal_pull: ["middle_back", "lats", "biceps"],
  rear_delt: ["shoulders", "middle_back"],
  elbow_flexion: ["biceps"],
  squat: ["quadriceps", "glutes", "hamstrings"],
  hinge: ["glutes", "hamstrings", "lower_back"],
  carry: ["middle_back", "lower_back"],
};

function daysAgo(days) {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

function createSet(id, weight, reps) {
  return {
    id,
    weight: String(weight),
    reps: String(reps),
    type: "S",
    done: true,
    rpe: "",
    rir: "",
    failure: false,
    note: "",
  };
}

function createExercise(id, name, libraryId, movementPattern, weight, reps, setCount) {
  return {
    id,
    libraryId,
    name,
    target: `${setCount} sets - ${reps} reps`,
    image: "/exercise-images/trackfit-fallback.svg",
    primaryMuscles: MUSCLES_BY_PATTERN[movementPattern] || [],
    equipment: ["gym"],
    movementPattern,
    defaultRestSeconds: 90,
    exerciseNote: "",
    sets: Array.from({ length: setCount }, (_, index) =>
      createSet(`${id}-set-${index + 1}`, weight, reps),
    ),
  };
}

function calculateWorkoutVolume(exercises) {
  return exercises.reduce(
    (workoutTotal, exercise) =>
      workoutTotal +
      exercise.sets.reduce((setTotal, set) => {
        const weight = Number(set.weight || 0);
        const reps = Number(set.reps || 0);
        return setTotal + weight * reps;
      }, 0),
    0,
  );
}

function createWorkout(id, daysBack, title, exercises, prs = []) {
  const completedSets = exercises.reduce((sum, exercise) => sum + exercise.sets.length, 0);
  const volume = calculateWorkoutVolume(exercises);

  return {
    id,
    workoutId: id.includes("upper")
      ? "demo-plan-upper-strength"
      : id.includes("lower")
        ? "demo-plan-lower-strength"
        : id.includes("push")
          ? "demo-plan-push-volume"
          : "demo-plan-pull-volume",
    title,
    completedAt: daysAgo(daysBack),
    seconds: 2700 + daysBack * 45,
    durationSeconds: 2700 + daysBack * 45,
    completedSets,
    totalSets: completedSets,
    volume,
    prs,
    exercises,
    notes: "Generated by the TrackFit Demo Athlete Generator.",
  };
}

function adjustedWeight(baseWeight, weekIndex, settings) {
  const progress = settings.plateau && weekIndex >= 2 ? settings.progressStep : settings.progressStep * weekIndex;
  const adjusted = (baseWeight + progress) * settings.volumeMultiplier;

  return Math.round(adjusted * 2) / 2;
}

function createWeekWorkouts(weekIndex, settings) {
  const weekOffset = weekIndex * 7;
  const prs = weekIndex === 3 && !settings.plateau
    ? [{ type: "Estimated 1RM", exercise: "Barbell Bench Press", value: "New demo PR" }]
    : [];

  return [
    createWorkout(`athlete-upper-${weekIndex}`, weekOffset, "Upper Strength", [
      createExercise(`athlete-bench-${weekIndex}`, "Barbell Bench Press", "barbell-bench-press-medium-grip", "horizontal_push", adjustedWeight(75, weekIndex, settings), 6, 4),
      createExercise(`athlete-row-${weekIndex}`, "Barbell Rear Delt Row", "barbell-rear-delt-row", "horizontal_pull", adjustedWeight(50, weekIndex, settings), 10, 3),
      createExercise(`athlete-press-${weekIndex}`, "Barbell Shoulder Press", "barbell-shoulder-pres", "vertical_push", adjustedWeight(40, weekIndex, settings), 8, 3),
    ], prs),
    createWorkout(`athlete-lower-${weekIndex}`, weekOffset + 2, "Lower Strength", [
      createExercise(`athlete-lunge-${weekIndex}`, "Barbell Lunge", "barbell-lunge", "squat", adjustedWeight(50, weekIndex, settings), 8, 4),
      createExercise(`athlete-bridge-${weekIndex}`, "Barbell Glute Bridge", "barbell-glute-bridge", "hinge", adjustedWeight(95, weekIndex, settings), 10, 4),
      createExercise(`athlete-shrug-${weekIndex}`, "Barbell Shrug", "barbell-shrug", "carry", adjustedWeight(85, weekIndex, settings), 12, 3),
    ]),
    createWorkout(`athlete-push-${weekIndex}`, weekOffset + 4, "Push Volume", [
      createExercise(`athlete-incline-${weekIndex}`, "Incline Bench Press", "barbell-incline-bench-press-medium-grip", "horizontal_push", adjustedWeight(57.5, weekIndex, settings), 10, 3),
      createExercise(`athlete-guillotine-${weekIndex}`, "Guillotine Bench Press", "barbell-guillotine-bench-press", "horizontal_push", adjustedWeight(47.5, weekIndex, settings), 10, 3),
      createExercise(`athlete-press-volume-${weekIndex}`, "Barbell Shoulder Press", "barbell-shoulder-pres", "vertical_push", adjustedWeight(37.5, weekIndex, settings), 9, 3),
    ]),
    createWorkout(`athlete-pull-${weekIndex}`, weekOffset + 6, "Pull Volume", [
      createExercise(`athlete-row-volume-${weekIndex}`, "Barbell Rear Delt Row", "barbell-rear-delt-row", "horizontal_pull", adjustedWeight(50, weekIndex, settings), 12, 4),
      createExercise(`athlete-band-fly-${weekIndex}`, "Back Flyes With Bands", "back-flyes-with-bands", "rear_delt", adjustedWeight(12.5, weekIndex, settings), 12, 3),
      createExercise(`athlete-curl-${weekIndex}`, "Barbell Curl", "barbell-curl", "elbow_flexion", adjustedWeight(32.5, weekIndex, settings), 10, 3),
    ]),
  ];
}

function createHistory(settings) {
  const workouts = Array.from({ length: 6 }, (_, weekIndex) => createWeekWorkouts(weekIndex, settings)).flat();

  if (settings.fatiguePattern !== "heavy") return workouts;

  return [
    createWorkout("athlete-extra-fatigue-1", 1, "Extra Conditioning", [
      createExercise("athlete-fatigue-row", "Barbell Rear Delt Row", "barbell-rear-delt-row", "horizontal_pull", adjustedWeight(52.5, 5, settings), 12, 4),
      createExercise("athlete-fatigue-curl", "Barbell Curl", "barbell-curl", "elbow_flexion", adjustedWeight(35, 5, settings), 10, 3),
    ]),
    ...workouts,
  ];
}

function createCheckIns(settings) {
  return Array.from({ length: 42 }, (_, index) => ({
    id: `athlete-checkin-${index}`,
    date: daysAgo(index),
    protein: Math.round(settings.proteinBase + (index % 5) * 4),
    water: Math.round((settings.waterBase + (index % 4) * 0.15) * 10) / 10,
    sleep: Math.round((settings.sleepBase + (index % 5) * 0.2) * 10) / 10,
    trained: [0, 1, 2, 4, 6, 8, 11, 14, 16, 18, 21, 23, 25, 28, 30, 32, 35, 37, 39].includes(index),
    weight: Math.round((settings.weightStart - index * 0.05) * 10) / 10,
  }));
}

function createCardio(settings) {
  const hardMode = settings.fatiguePattern === "heavy";

  return [
    { id: "athlete-cardio-1", date: daysAgo(0), type: "Incline Walk", distance: 3.4, duration: 28 },
    { id: "athlete-cardio-2", date: daysAgo(2), type: hardMode ? "Rower" : "Bike", distance: hardMode ? 2.4 : 8.8, duration: hardMode ? 14 : 24 },
    { id: "athlete-cardio-3", date: daysAgo(4), type: "Walk", distance: 4.2, duration: 39 },
    { id: "athlete-cardio-4", date: daysAgo(7), type: "Incline Walk", distance: 3.1, duration: 26 },
    { id: "athlete-cardio-5", date: daysAgo(14), type: "Incline Walk", distance: 3.8, duration: 32 },
    { id: "athlete-cardio-6", date: daysAgo(21), type: "Walk", distance: 4.6, duration: 42 },
  ];
}

export function generateDemoAthlete(profile = "intermediate") {
  const settings = PROFILE_SETTINGS[profile] || PROFILE_SETTINGS.intermediate;

  // Seed the normal demo data first so the AI plan and active workouts exist.
  seedDemoData();

  // Then replace only the athlete-specific history, check-ins and cardio.
  HistoryRepository.saveAll(createHistory(settings));
  CheckInRepository.saveAll(createCheckIns(settings));
  CardioRepository.saveAll(createCardio(settings));

  return {
    profile,
    label: settings.label,
    historyCount: HistoryRepository.getAll().length,
    checkInCount: CheckInRepository.getAll().length,
    cardioCount: CardioRepository.getAll().length,
  };
}

export const DEMO_ATHLETE_PROFILES = [
  { id: "beginner", label: "Beginner athlete" },
  { id: "intermediate", label: "Intermediate athlete" },
  { id: "plateau", label: "Plateau athlete" },
  { id: "fatigued", label: "Fatigued athlete" },
];

/**
 * ============================================================================
 * DEVELOPER NOTES
 * ============================================================================
 *
 * This generator deliberately uses predictable fake data.
 *
 * Predictable is good here because bugs are easier to chase.
 *
 * If a Coach card changes, we want to know whether the change came from:
 *
 * 1. the fake athlete profile
 * 2. the repository data
 * 3. the Coach engine
 * 4. the UI card
 *
 * Keep this file simple. Fancy random generators are fun, but repeatable data is
 * much better for debugging.
 *
 * ============================================================================
 */
